### ISSUE TITLE
Is the Software licensing check a requirement?

### ISSUE THREAD

**Issue by jonathanbossenger** [rtCamp/woocommerce-to-easydigitaldownloads#5]
First off, this is a great script, I am looking into ways of migrating from WC to EDD and this may save me many hours of development.

I notice that you do a check for WC, EDD and the Software License extension, is that third check a requirement? The reason I ask is that we don't use any current software licensing extensions for WC so I don't need to migrate any license data at the moment. 

Thanks again for this great script.

**Comment by rahul286** [comment]
@jonathanbossenger we used woocommerce software licensing addon. We primary sale WordPress themes and plugins. That is the reason we needed software licensing.

Feel free to fork, modify and use codes. There are many parts which were specific to our needs. That is a reason we did release as this a plugin.
