### ISSUE TITLE
WC &  EDD is not activated

### ISSUE THREAD

**Issue by mehedi-sharif** [rtCamp/woocommerce-to-easydigitaldownloads#6]
Hello team,
Currently I am moving my woocommerce site to edd. I saw this script and follow the description.It shows this error
"WP Loaded ...
WC & EDD Not Activated."
I have already activated WC &  EDD. but no luck.. Any solution ?
Thanks in advance

**Comment by gt1987** [comment]
Hey, if you're sure that both of the plugins are activate you can simply remove the part of the code which is checking if they're active or not:

```
`include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
if ( ! is_plugin_active( 'woocommerce/woocommerce.php' ) || ! is_plugin_active( 'easy-digital-downloads/easy-digital-downloads.php' ) || ! is_plugin_active( 'edd-software-licensing/edd-software-licenses.php' ) ) {
	exit( "\nWC & EDD Not Activated.\n" );
}
$temp_log_str = "\nWC & EDD activated ...\n";
$log_str .= $temp_log_str;
echo $temp_log_str;`
```
And the script should simply skip to the next step!

**Comment by mehedi-sharif** [comment]
Thanks for your reply @gt1987  , I did that with another way.
Thanks

**Comment by adelbbj** [comment]
@mehedi-sharif hi, how did you do that?

**Comment by mehedi-sharif** [comment]
I had almost 30+ products . Export all the products in xml then open that export file and change the post type and thats all. You will get all yours products in EDD . But you have to change product thumbnails only. That was the task.
Thanks

**Comment by lukecav** [comment]
**edd-software-licensing** plugin also need to be active for the check to run.
https://easydigitaldownloads.com/downloads/software-licensing/
